export const ADD_SCENARIO = 'ADD_SCENARIO';
export const UPDATE_SCENARIO = 'UPDATE_SCENARIO';
export const DELETE_SCENARIO = 'DELETE_SCENARIO';
export const ADD_VEHICLE = 'ADD_VEHICLE';
export const UPDATE_VEHICLE = 'UPDATE_VEHICLE';
export const DELETE_VEHICLE = 'DELETE_VEHICLE';