export const ADD_SCENARIO_REQUEST = 'ADD_SCENARIO_REQUEST';
export const ADD_SCENARIO_SUCCESS = 'ADD_SCENARIO_SUCCESS';
export const ADD_SCENARIO_FAILURE = 'ADD_SCENARIO_FAILURE';


export const GET_SCENARIO_REQUEST = 'GET_SCENARIO_REQUEST';
export const GET_SCENARIO_SUCCESS = 'GET_SCENARIO_SUCCESS';
export const GET_SCENARIO_FAILURE = 'GET_SCENARIO_FAILURE';

export const UPDATE_SCENARIO_REQUEST = 'UPDATE_SCENARIO_REQUEST';
export const UPDATE_SCENARIO_SUCCESS = 'UPDATE_SCENARIO_SUCCESS';
export const UPDATE_SCENARIO_FAILURE = 'UPDATE_SCENARIO_FAILURE';


export const DELETE_SCENARIO_REQUEST = 'DELETE_SCENARIO_REQUEST';
export const DELETE_SCENARIO_SUCCESS = 'DELETE_SCENARIO_SUCCESS';
export const DELETE_SCENARIO_FAILURE = 'DELETE_SCENARIO_FAILURE';
